# Generated by Django 2.0 on 2018-12-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='purpose',
            field=models.CharField(max_length=200),
        ),
    ]
